sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
#    这里密码需要配置到idea的环境变量中
    password: ${DB_PASSWORD}
